spring:
  # todo 개발 데이터베이스 연결
  datasource:
#    Elastic Beanstalk 사용하기 위해 삭제
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true # Failed to execute SQL script statement 에러 발생 -> true 설정
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ...
            client-secret: ...
            scope:
              - email
              - profile


jwt:
  issuer: dongjun6343@gmail.com
  secret_key: dongurijun